import './globals.css'
import Header from './header'
import Footer from './footer'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kisa\'s Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp">
      <body>
        <div className='flex flex-col min-h-screen'>
          <Header />
          <main className='flex-1 max-w-4xl w-full mx-auto'>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
