import './globals.css'
import { Inter } from 'next/font/google'
import Header from './Header'
import Footer from './Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp">
      <body className='flex flex-col min-h-screen'>
        <Header />
        <main className='flex-1 max-w-4xl w-full mx-auto'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
